# Generated by Django 4.2.7 on 2023-12-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='user_id',
            new_name='user',
        ),
    ]
