# Generated by Django 4.2.7 on 2024-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
