# Generated by Django 4.2.7 on 2023-12-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_rename_user_id_timesheet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.IntegerField(),
        ),
    ]
