# Generated by Django 4.2.7 on 2024-02-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
