# Generated by Django 4.2.7 on 2023-12-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_timesheet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
