# Generated by Django 4.2.7 on 2024-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
